# Generated by Django 5.2.10 on 2026-02-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_product_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='include_vat',
            field=models.BooleanField(default=False, verbose_name='Inclure la TVA (20%)'),
        ),
    ]
